### ISSUE TITLE
How did you get padding on the right side of NvimTree?

### ISSUE THREAD

**Issue by notusknot** [nvoid-lua/nvoid#2]
I can’t find what setting shows the cursorline with one character of padding on the right of NvimTree.

**Comment by ysfgrgO7** [comment]
> I can’t find what setting shows the cursorline with one character of padding on the right of NvimTree.

Sorry man I can't understand exactly what do you want   
But If you have a code send and I will add it

**Comment by ysfgrgO7** [comment]
I can't understand what are you talking about  
Can you send a screen shot for what are you talking about

**Comment by notusknot** [comment]
Here's what it looks like for me:
![screen](https://user-images.githubusercontent.com/69602000/159184085-e4572e9f-fdce-4280-9d2f-092d3de3e63b.png)

And this is what it looks like in NVoid.
![screen](https://user-images.githubusercontent.com/69602000/159184168-6ffa7f65-78ce-4aa7-b6d5-3c8279f4d686.png)

You can see there is a bit of extra space on the cursorline, so the border isn't as sharp
