### ISSUE TITLE
I think it would be awesome if you put a screenshot of how it looks!

### ISSUE THREAD

**Issue by 2244josiah** [nvoid-lua/nvoid#5]
Hey, I believe many people would like this configuration but It'd be very awesome if you'd put a screenshot how it looks on the README.md because some people like to get a feel before installing.

**Comment by ysfgrgO7** [comment]
> Hey, I believe many people would like this configuration but It'd be very awesome if you'd put a screenshot how it looks on the README.md because some people like to get a feel before installing.

You can check the website but I will do it
