### ISSUE TITLE
Config file not used

### ISSUE THREAD

**Issue by Ghostytriickster** [nvoid-lua/nvoid#8]
Hello, when customizing the config file at ~/.config/nvim/lua/custom/nvoidrc.lua , saving and quitting, and restarting nvoid, the config isn't taken into account. Is there another config path I don't know about ? I believe the quick config guide only mentions this one.
![2022-09-15-162056_1280x800_scrot](https://user-images.githubusercontent.com/88532121/190428531-11d61203-1179-4c77-9929-c926b2ec4f6c.png)

**Comment by ysfgrgO7** [comment]
yeah, I'm not sure what is the problem but you can try updating your config and try to reinstall nvoid

**Comment by ysfgrgO7** [comment]
Is the problem solved?

**Comment by Ghostytriickster** [comment]
no, I tried reinstalling nvoid, nvim, and even tried on my old laptop with another distribution to see if it would work better

**Comment by ysfgrgO7** [comment]
can you share the config file?

**Comment by Ghostytriickster** [comment]
sure, do you want me to compress it into a tarball or something ? github doesn't support dot lua files

**Comment by Ghostytriickster** [comment]
well, github's "enter code" thing didn't work really well, there's no ` at the start and end of the file

**Comment by ysfgrgO7** [comment]
There is a missing comma at line 52 `blankline = true,`

I also realized that lua lsp is not installed make sure you have wget, curl, unzip and it will help you spot errors

**Comment by Ghostytriickster** [comment]
ah, thanks, I’ll make sure to try that as soon as I can. I will get back to you with the results, thank you very much !

**Comment by Ghostytriickster** [comment]
just fixed the missing comma, sorry for being blind, and thank you for being patient

**Comment by ysfgrgO7** [comment]
No problem
